#!/bin/sh
killall ideservd 2>/dev/null

C64_IP=192.168.2.2
C64_NET=00

#ifconfig eth1 10.11.14.63
mkdir -p /tmp/pclink; chmod 1777 /tmp/pclink

arp -s $C64_IP 49:44:45:36:34:$C64_NET
exec ./ideservd --root=/tmp/pclink --user nobody --group nogroup --ipaddress $C64_IP --network 0x$C64_NET $@
# --log /dev/tty5 $@
